version: '4'
services:
  backend:
    image: filrouge
    build: filrouge
    ports:
      - "5000:5000"
    depends_on:
      - DB
  frontend:
    image: filrougefront
    build: filrougefront
    ports:
      - "5173:5173"
    depends_on:
      - backend
  DB: 
    image: mongo
    container_name: mongo
    command: mongod --port 27017
    ports:
      - "27017:27017"